### ISSUE TITLE
需要有著作權聲明

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#10]
放footer，或是獨立一頁皆可。主要文案內容如下：
1.本站內容統一採姓名標示-非商業性-相同方式分享 4.0 國際 (CC BY-NC-SA 4.0)釋出。
2.從立法院網站來源的資料，如立委照片、公報內容等，必須在遵守立法院的著作權規範之下取用。
3.如果在其他著作權方面有疑慮、建議或是想取得更進一步授權，請來信 lab@watchout.tw

**Comment by chihaoyo** [comment]
更新預設授權條款 https://github.com/watchout-tw/watchout-tw.github.io/commit/750017b9ee460c56e29762b71bb3bf031c4395d0
