### ISSUE TITLE
提案連署統計：政黨分組計數人數總計 / 名單顯示有問題需調整

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#12]
提案跟連署的人總計時，重複需排除，以 data-reports/3 來說，時力總共就5人，因為沒有排除重複變成7人。

如果排除重複比較麻煩。那可能在統計上要調整成拆成2個長條圖：提案一個，連署一個。

看是排除重複，或是拆成兩個圖表，兩種作法我覺得都是ok的。

以 data-reports/4 來說，費鴻泰是首位提案人，但是在上面長條圖中國國民黨只有連署人，沒有提案人資料。民進黨的首位提案人也不只一位但只顯示了王定宇。

以 data-reports/3 來說，首位提案人 / 共同提案人 / 連署人 名單都有缺漏。

**Comment by chihaoyo** [comment]
人數計算方式已調整 a2fa32337b2e72d97a0eb8de4ca6ed6bdd90c947

**Comment by chihaoyo** [comment]
@buttom 這裡還有問題嗎？

**Comment by buttom** [comment]
@chihaoyo 
/data-reports/4 政黨分組計數人數總計，民進黨提案有9個。但這裡的首位提案名單只有7人，少了陳亭妃，葉宜津，因為他們同時有連署，結果在上面名單反而被過濾掉了。

抱歉這部分需求是我沒想得太詳細。規則需要調整成這樣：
1.如果他同時有首位提案，也有連署，那他名字在首位提案跟連署都要列出，假設有個人自己有首位提案，也有共同提案，也有連署，那他名字就會出現三次。
2.但是總計算的人數要扣除重複。例如陳亭妃只算一次，葉宜津也只算一次

**Comment by buttom** [comment]
希望改善日期：10/27

**Comment by chihaoyo** [comment]
這個應該已經OK了？

**Comment by buttom** [comment]
@chihaoyo 剛上beta跟正式機看，這個問題還是在-->「/data-reports/4 政黨分組計數人數總計，民進黨提案有9個。但這裡的首位提案名單只有7人，少了陳亭妃，葉宜津，因為他們同時有連署，結果在上面名單反而被過濾掉了。」

但總計算的人數要扣除重複的部分是ok了。

**Comment by chihaoyo** [comment]
`CORE`更新演算法 https://github.com/watchout-tw/core/pull/125 麻煩 @buttom 再看一次！

**Comment by buttom** [comment]
正確了，謝啦！
