### ISSUE TITLE
提案連署統計：政黨比例的數據有問題

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#14]
以 data-reports/6/ 為例子，親民黨只有1人為提案人，不分區一共3人，比例應該是30.33，但算出來卻是50%。

data-reports/3/ ， data-reports/11 ，第九屆無黨籍只有1 個。但這裡算出來的無黨籍政黨比例都是 50% (應該是100%）

**Comment by buttom** [comment]
data-reports/3/ ， data-reports/11  ，第九屆無黨籍只有1 個。但這裡算出來的無黨籍政黨比例都是 50% (應該是100%）

**Comment by buttom** [comment]
/data-reports/6
有點不確定問題出在哪...國民黨的比例是對的。民進黨的比例是算起來很接近但就是差一點。親民黨的比例是錯的，但我去後臺看確定親民黨我灌入的第九屆資料是對的。無黨籍是錯的，後台第九屆資料輸入核對過也是正確的。

**Comment by chihaoyo** [comment]
Mock data updated 4d302cd8349d9bd1fe094279bf11a5b3d29026fa

**Comment by chihaoyo** [comment]
目前使用mock data，直接把各政黨人數寫在程式碼裡面 https://github.com/watchout-tw/lab/blob/c4600ea2650b2a28cdeb7e7de2521efa43980d39/src/components/Figure/SpsrPartisanPct.vue#L49 [GET /c0ngress/reps](https://core-docs.watchout.tw/c0ngress/reps)API正在開發，完成並測試後，會使用API即時統計系統內各政黨人數，也可以支援任兩個時間點之間的委員人數。

**Comment by watchout-dev** [comment]
我覺得先這樣解ok。因為實際這個數字即時變化的程度很低。

**Comment by buttom** [comment]
我覺得先這樣解ok。因為實際各政黨總人數這個數字的即時變化程度很低。

**Comment by chihaoyo** [comment]
@buttom 這個應該OK了？

**Comment by buttom** [comment]
ok了。數值正確。
