### ISSUE TITLE
提案連署統計：同一委員如果有重複提案一起比較，其中一個人際網路線會沒畫出來

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#16]
國體法 data-reports/13/ 為例子。因為黃國書一開始提的是專法，後來提國體法。但內容項目是可以一起比較的，所以我放在一起。在圖表上黃國書另外一個人際網路就沒有線。

**Comment by wesley100002001** [comment]
Solved. bcc9b0b11a19309906a80be1c05a485c7c5f2d91
