### ISSUE TITLE
議題頁底下數據分析報告，需更明顯可點擊的提示

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#23]
1.目前外部訪談有4人表示我如果沒有提他們不知道可以按，內部夥伴也有先聽到2位反應第一眼看過去不知道可以點。
2.GA的數據顯示網站通過率不佳。

希望改善日期：10/20

**Comment by chihaoyo** [comment]
8c712929626a6d01ae68ccfd8e148f83ba25f3cd
