### ISSUE TITLE
適當使用<h1>...<h6>標籤

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/lab#3]
- [x] 議題綜覽列表的`<div class="tagline">`改用`<h3>`

**Comment by chihaoyo** [comment]
@buttom 好奇如果這裡不用`<h3>`而用`<h4>`、`<h5>`或`<h6>`，會對於indexing或SEO有什麼影響嗎？

**Comment by buttom** [comment]
@chihaoyo 我不敢說有很大影響，不過原則上以內容權重來說，h數字越小權重越大。然後google本身在搜尋結果會有一個特色，就是搜不同關鍵字，同一頁面他可能會擷取顯示不同標題（如果你內文有多標題且他判斷某標題跟搜尋字詞相關性更高的話）

所以我習慣凡事直接內容的標題都照重要性分配h數字，越重要的數字越小，用過依序跳下號。而如果是文章內文需要標題分段，這種在同一篇文內大量出現的小標題我習慣從h3開始用。屬於內文主體的我通常會蠻大量用h3，最多到h4。

像h5，h6我會習慣用在整體頁面也算相當小重點但不像主內容那麼重要的文字上，例如我們現在議題單頁每段文字底下的圖表標題。或是到時應另外顯示出修法方向，那修法方向我就會用h5。圖表名稱用h6。

整體原則就是我們覺得哪些標題對使用者來說權重要高一點，那就用h。
