### ISSUE TITLE
發言圖表頁：委員發言立場統計圓餅圖的次數跟圓圈大小比例須調整

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#33]
以 /data-reports/15 為例子，尤美女的四次跟王玉敏的一次之間差異太大。比例希望可以調整一下。我之前自己畫的sample，一次跟四次的倍數增加是用「圓形面積」的四倍，不是用「半徑」四倍，這樣圓圈比較不會大的那麼誇張。

現在這樣也容易造成發言圓餅圖要滑一陣子才能看完全部，沒辦法一眼看完。雖然發言次數多的時候多少會這樣，但還是希望可以縮小滑的長度。

**Comment by buttom** [comment]
希望完成日期：11月24日。

**Comment by chihaoyo** [comment]
https://github.com/watchout-tw/lab/commit/ba95242d1c8e86a07173858fc4be5a666e38dbf2
