### ISSUE TITLE
1月SEO文案更新：勞基法 / 年金改革 / 既有頁面 title 調整

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#53]
先註記一下，等這個月所有分析文版面都組好（勞基法有一些出了，還有發言要上跟組版，年金改革還沒組）再一次跟 @wesley100002001  討論確認更新時間。

**Comment by buttom** [comment]
記錄一下在議題實驗室尚未能透過資料庫更新SEO文字的暫時做法
1.整理的文案僅供 joy 自己未來可進資料庫更新時再更換，給 @wesley100002001  看主要是看有哪些新頁面的id（包含圖表分析頁 & 議題總覽）
2.在尚未能跟資料庫連結更動前，先照目前已經有寫好的seo文案規則，每個月一次整批生成更新。

**Comment by wesley100002001** [comment]
已更新完畢，之後有需求再新開 issue～
