### ISSUE TITLE
議題縱覽頁：後台從編輯議題綜覽新增一個全新的議題後，設定草稿前台看該頁面是空的，設定上稿會造成首頁議題列表無法顯示

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#55]
議題縱覽頁：後台從編輯議題綜覽新增一個全新的議題後，設定為草稿接著去前台看該頁面是空的沒有文字，改設定上稿會造成首頁議題列表無法顯示

**Comment by wesley100002001** [comment]
@buttom 議題綜覽的「圖像」如果有設定好，一樣會有此狀況嗎？

**Comment by buttom** [comment]
@wesley100002001  看起來好像是卡在「圖像」要設定「正確」，我用別的確認存在的圖像po就ok了。

**Comment by buttom** [comment]
@wesley100002001  想問一下，因為我有看到 @chihaoyo  在這
https://github.com/watchout-tw/lab/commit/81ccc92880f706252b5f57a20b4ea7369047e3cd
已經有設計好的圖檔了，但我如果直接把圖檔檔名 pension_reform.png 貼到中控室，他議題縱覽就沒辦法正常顯示，這張圖能否幫我放到正確的路徑？

**Comment by buttom** [comment]
年金改革圖稿已上prd

**Comment by wesley100002001** [comment]
圖片路徑我在 local 測試看起來是沒有問題的，如果 staging 也有一樣的問題，再麻煩 @buttom 回報
