### ISSUE TITLE
提案比較分析頁的「未修法」小字套用字串改成「未修改」

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#56]
以
https://lab.watchout.tw/data-reports/35
為例子。之前如果在後台輸入「未修法」，這個頁面前端有自動讓「未修法」三個字比較小一點顏色也比較淺一點。但後來在順文字的時候覺得「未修改」對一般人更好懂，所以後來我都改用「未修改」取代「未修法」。所以現在「未修改」的字就會跟一般修法內容一樣，這部分希望調整成跟之前一樣稍微小一點。

**Comment by wesley100002001** [comment]
已調整
