### ISSUE TITLE
增加長期照顧議題用圖

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/lab#59]
https://github.com/watchout-tw/lab/commit/3b2961f41d04bda3472af40fe8d04d4ce46f5251

麻煩@wesley100002001在deploy時稍微注意即可。

**Comment by buttom** [comment]
@wesley100002001 圖檔我設定 long_term_care.png ，但議題頁內容會出不來，要先換成一張之前就存在的其他議題圖才會顯示正常，這張圖檔再幫我確認一下。

**Comment by wesley100002001** [comment]
@buttom 已經完成，可以幫我測試

**Comment by buttom** [comment]
測試ok
