### ISSUE TITLE
圖表頁需顯示「修法方向」為何。

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#6]
以集遊法為例子，修法方向有兩個，且正好有一個立委，在某一修法方向是沒有提的。但另一個有提。如果他同時有兩個不同修法方向的同一類型圖表，現在畫面上沒有標示哪一個修法方向，就會不知道為什麼會分這兩頁出來。

看是否圖表頁的h1如果預設沒輸入自動標題的時候，就先以「修法方向+圖表頁名稱」作為預設標題。
例如「下修罷免門檻提案比較」「下修罷免門檻提案連署統計」

**Comment by chihaoyo** [comment]
數據分析報告已於`<header>`中以`<h3>`顯示修法方向。
