### ISSUE TITLE
提案比較：法案比較得分的「得分標示文字」需要顯示

### ISSUE THREAD

**Issue by buttom** [watchout-tw/lab#9]
以 data-report/2 為例，我文字上會寫一下為什麼大家的分數會這樣評比，誰高分的原因是什麼這類的。但目前圖表上沒有顯示x分對應的內容大概是什麼，這樣我上面的文字讀者讀起來會顯得無中生有。所以得分標示對應的文字還是必須要顯示出來。

**Comment by buttom** [comment]
希望改善日期：10/27

**Comment by chihaoyo** [comment]
8fe42a1b324960c15638e3982ebec77d690515df `BillCompBars`顯示法案比較量尺的分數敘述。

**Comment by buttom** [comment]
beta 測試 ok。
